server:
  port: 8082
spring:
  application:
    name: closet
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  batch:
    datasource:
      jdbcUrl: ${BATCH_DATASOURCE_URL:jdbc:postgresql://localhost:5432/closet-batch}
      driver-class-name: org.postgresql.Driver
      username: ${DATABASE_USERNAME:closet-user}
      password: ${DATABASE_PASSWORD:closet_1234}
    job:
      enabled: false
    jdbc:
      initialize-schema: never

  business:
    datasource:
      jdbcUrl: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/closet}
      driver-class-name: org.postgresql.Driver
      username: ${DATABASE_USERNAME:closet-user}
      password: ${DATABASE_PASSWORD:closet_1234}

management:
  server:
    port: 9103
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true
closet:
  weather:
    api:
      base-url: https://apis.data.go.kr/1360000/VilageFcstInfoService_2.0
      service-key: ${KMA_SERVICE_KEY:dummyKey}
      timeout: 10000
      data-type: JSON

logging:
  level:
    root: INFO
    org.hibernate.SQL: OFF
    org.hibernate.type.descriptor.sql: OFF